const categoriesData = [
  {
    name: 'Vegetables',
    slug: 'vegetables',
    description: 'Fresh seasonal vegetables, leafy greens, roots, and culinary aromatics directly harvested from local farms.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Fruits',
    slug: 'fruits',
    description: 'Naturally tree-ripened orchard fruits, seasonal berries, and native heirloom varieties.',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Dairy',
    slug: 'dairy',
    description: 'Farm-fresh milk, cultured A2 bilona ghee, artisanal paneer, and farm butter.',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Grains',
    slug: 'grains',
    description: 'Unpolished traditional rice varieties, heirloom wheat, millets, and stone-ground flours.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Pulses',
    slug: 'pulses',
    description: 'Unpolished protein-rich lentils, chickpeas, black gram, and pigeon peas straight from the field.',
    image: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Spices',
    slug: 'spices',
    description: 'Single-origin sun-dried whole and ground spices retaining full natural essential oils and aroma.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Organic Produce',
    slug: 'organic-produce',
    description: '100% certified pesticide-free vegetables, herbs, and superfoods grown using regenerative methods.',
    image: 'https://images.unsplash.com/photo-1506484381205-f7945653044d?auto=format&fit=crop&w=600&q=80',
    active: true
  },
  {
    name: 'Other',
    slug: 'other',
    description: 'Cold-pressed farm oils, raw forest honey, jaggery, and farm-crafted natural preserves.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    active: true
  }
];

const adminData = {
  name: 'Platform Administrator',
  email: 'admin@krishidirect.com',
  phone: '+91 98765 00000',
  password: 'AdminPass123!',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  status: 'active'
};

const farmersData = [
  {
    name: 'Ramesh Patel',
    email: 'ramesh.patel@farm.com',
    phone: '+91 98201 11223',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Green Valley Organic Farm',
      location: 'Dindori Taluk',
      district: 'Nashik',
      state: 'Maharashtra',
      pincode: '422202',
      description: 'Family-owned 15-acre organic farm cultivating vine tomatoes, exotic bell peppers, and fresh greens using drip irrigation and bio-compost.',
      cropTypes: ['Vegetables', 'Organic Produce', 'Grains'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['NPOP India Organic', 'PGS-India Green'],
      yearsExperience: 14,
      farmSizeAcres: 15,
      verificationStatus: 'approved',
      rating: 4.9,
      reviewCount: 48,
      fulfilmentRate: 99,
      deliveryOptions: ['Local delivery', 'Scheduled delivery', 'Farm pickup'],
      typicalDeliveryDays: 'Same Day - 1 Day',
      minimumOrder: 200,
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Harvested at 5:00 AM each morning, naturally sorted, packed in breathable jute hampers.',
      sourcingTransparency: '100% single-origin farm harvest with zero external wholesale aggregation.'
    }
  },
  {
    name: 'Sunita Devi',
    email: 'sunita.devi@farm.com',
    phone: '+91 94152 22334',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Devi Natural Agro Sanctuary',
      location: 'Chiraigaon',
      district: 'Varanasi',
      state: 'Uttar Pradesh',
      pincode: '221112',
      description: 'Championing chemical-free subhash palekar natural farming (ZBNF) across 9 acres along the fertile Gangetic belt.',
      cropTypes: ['Pulses', 'Spices', 'Vegetables'],
      farmingMethod: 'Natural / Permaculture',
      organicCertified: true,
      certifications: ['PGS-India Green'],
      yearsExperience: 9,
      farmSizeAcres: 9,
      verificationStatus: 'approved',
      rating: 4.8,
      reviewCount: 36,
      fulfilmentRate: 97,
      deliveryOptions: ['Scheduled delivery', 'Local delivery'],
      typicalDeliveryDays: '1-2 Days',
      minimumOrder: 150,
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Sun-dried naturally, hand-sorted pulses with no chemical polishing or artificial coloring.',
      sourcingTransparency: 'Certified chemical-free natural farming directly managed by women farmer collective.'
    }
  },
  {
    name: 'Gurpreet Singh',
    email: 'gurpreet.singh@farm.com',
    phone: '+91 98140 33445',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Doaba Golden Grain Farm',
      location: 'Phagwara Road',
      district: 'Jalandhar',
      state: 'Punjab',
      pincode: '144001',
      description: 'Specializing in heirloom Sharbati wheat, Basmati rice, and cold-pressed pure mustard oil from generational alluvial soil.',
      cropTypes: ['Grains', 'Other'],
      farmingMethod: 'Conventional',
      organicCertified: false,
      certifications: ['FSSAI Registered', 'Agmark Certified'],
      yearsExperience: 22,
      farmSizeAcres: 28,
      verificationStatus: 'approved',
      rating: 4.7,
      reviewCount: 52,
      fulfilmentRate: 98,
      deliveryOptions: ['Scheduled delivery', 'Farm pickup'],
      typicalDeliveryDays: '2 Days',
      minimumOrder: 300,
      profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Grain cleaned in multi-tier gravity separators, moisture-controlled storage in food-grade silos.',
      sourcingTransparency: 'Generational farm with precision irrigation and documented harvest tracking.'
    }
  },
  {
    name: 'K. Venkatraman',
    email: 'k.venkatraman@farm.com',
    phone: '+91 94431 44556',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Kaveri Delta Heritage Farm',
      location: 'Papanasam',
      district: 'Thanjavur',
      state: 'Tamil Nadu',
      pincode: '614205',
      description: 'Preserving traditional indigenous paddy varieties such as Mapillai Samba, Karuppu Kavuni, and tender coconut orchards.',
      cropTypes: ['Grains', 'Fruits', 'Organic Produce'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['NPOP India Organic', 'Jaivik Bharat'],
      yearsExperience: 16,
      farmSizeAcres: 12,
      verificationStatus: 'approved',
      rating: 4.9,
      reviewCount: 41,
      fulfilmentRate: 99,
      deliveryOptions: ['Local delivery', 'Scheduled delivery'],
      typicalDeliveryDays: '1-2 Days',
      minimumOrder: 250,
      profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Traditional hand harvesting followed by stone milling without stripping nutrient bran.',
      sourcingTransparency: 'Ancient heritage grains grown with Kaveri river water and farm-made jeevamrit.'
    }
  },
  {
    name: 'Anita Deshmukh',
    email: 'anita.deshmukh@farm.com',
    phone: '+91 98220 55667',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Sahyadri Agro Orchards',
      location: 'Narayangaon',
      district: 'Pune',
      state: 'Maharashtra',
      pincode: '410504',
      description: 'Cultivating crunchy seedless pomegranates, guava, and fresh culinary herbs on sunny Sahyadri foothills.',
      cropTypes: ['Fruits', 'Vegetables'],
      farmingMethod: 'Natural / Permaculture',
      organicCertified: false,
      certifications: ['GlobalGAP Compliant'],
      yearsExperience: 8,
      farmSizeAcres: 10,
      verificationStatus: 'approved',
      rating: 4.6,
      reviewCount: 29,
      fulfilmentRate: 96,
      deliveryOptions: ['Local delivery', 'Farm pickup'],
      typicalDeliveryDays: '1 Day',
      minimumOrder: 180,
      profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Harvested only when naturally brix-tested for optimal sweetness, cushioned in recyclable trays.',
      sourcingTransparency: 'Certified residue-free orchard farming with solar powered cold holding.'
    }
  },
  {
    name: 'Balaram Gowda',
    email: 'balaram.gowda@farm.com',
    phone: '+91 94481 66778',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Malnad Rainforest Spices',
      location: 'Thirthahalli',
      district: 'Shivamogga',
      state: 'Karnataka',
      pincode: '577432',
      description: 'Shade-grown organic black pepper, Malabar green cardamom, and fresh wild turmeric beneath areca nut canopies.',
      cropTypes: ['Spices', 'Organic Produce'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['NPOP India Organic', 'Fair Trade Certified'],
      yearsExperience: 18,
      farmSizeAcres: 14,
      verificationStatus: 'approved',
      rating: 4.9,
      reviewCount: 64,
      fulfilmentRate: 100,
      deliveryOptions: ['Scheduled delivery'],
      typicalDeliveryDays: '2-3 Days',
      minimumOrder: 200,
      profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Sun-dried on bamboo mats, hand-graded by berry density, sealed in aroma-lock glass and tin containers.',
      sourcingTransparency: 'Forest-friendly polyculture agroforestry supporting local biodiversity.'
    }
  },
  {
    name: 'Rajesh Verma',
    email: 'rajesh.verma@farm.com',
    phone: '+91 98160 77889',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Himalayan Ridge Orchards',
      location: 'Kotgarh',
      district: 'Shimla',
      state: 'Himachal Pradesh',
      pincode: '172031',
      description: 'High-altitude Royal Delicious apples, Himalayan mountain garlic, and wild apricot kernels grown above 7,000 feet.',
      cropTypes: ['Fruits', 'Vegetables', 'Organic Produce'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['PGS-India Green', 'Zero Chemical Certified'],
      yearsExperience: 13,
      farmSizeAcres: 8,
      verificationStatus: 'approved',
      rating: 4.8,
      reviewCount: 38,
      fulfilmentRate: 98,
      deliveryOptions: ['Scheduled delivery'],
      typicalDeliveryDays: '2-3 Days',
      minimumOrder: 350,
      profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Hand-plucked directly with cotton gloves to prevent bruising, non-waxed pure peel.',
      sourcingTransparency: 'Glacier-fed mountain soil without synthetic growth retardants or synthetic waxes.'
    }
  },
  {
    name: 'Hitesh Barot',
    email: 'hitesh.barot@farm.com',
    phone: '+91 98250 88990',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Gir Amrut A2 Dairy & Farm',
      location: 'Talala Road',
      district: 'Junagadh',
      state: 'Gujarat',
      pincode: '362150',
      description: 'Ethical cruelty-free indigenous Gir cow sanctuary producing hand-churned A2 Bilona ghee, Gir kesar mangoes, and sesame.',
      cropTypes: ['Dairy', 'Fruits', 'Other'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['NPOP India Organic', 'FSSAI Certified'],
      yearsExperience: 11,
      farmSizeAcres: 20,
      verificationStatus: 'approved',
      rating: 4.9,
      reviewCount: 72,
      fulfilmentRate: 100,
      deliveryOptions: ['Local delivery', 'Scheduled delivery'],
      typicalDeliveryDays: '1-2 Days',
      minimumOrder: 400,
      profileImage: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Ancient Vedic curd-churning method using wooden bilona at sunrise over slow cow dung embers.',
      sourcingTransparency: 'Cows free-graze in pristine Gir forest medicinal pastures. Calves fed first.'
    }
  },
  {
    name: 'Meenakshi Sundaram',
    email: 'meenakshi.s@farm.com',
    phone: '+91 94420 99001',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Nilgiri Mist Hydro Greens',
      location: 'Coonoor Road',
      district: 'The Nilgiris',
      state: 'Tamil Nadu',
      pincode: '643101',
      description: 'High-tech solar-powered closed-loop hydroponic farm growing crisp butterhead lettuce, kale, basil, and baby spinach.',
      cropTypes: ['Vegetables', 'Organic Produce'],
      farmingMethod: 'Hydroponic',
      organicCertified: true,
      certifications: ['Zero Pesticide Residue', 'Clean Hydro Certified'],
      yearsExperience: 6,
      farmSizeAcres: 4,
      verificationStatus: 'approved',
      rating: 4.9,
      reviewCount: 45,
      fulfilmentRate: 99,
      deliveryOptions: ['Local delivery', 'Scheduled delivery'],
      typicalDeliveryDays: 'Same Day - 1 Day',
      minimumOrder: 220,
      profileImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Roots intact with live sponge block to maintain garden freshness in the kitchen for up to 10 days.',
      sourcingTransparency: '90% less water usage compared to conventional farming. Clean UV filtered mountain spring water.'
    }
  },
  {
    name: 'Devendra Choudhary',
    email: 'devendra.c@farm.com',
    phone: '+91 94140 10203',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Marwar Desert Eco Agro',
      location: 'Bilara',
      district: 'Jodhpur',
      state: 'Rajasthan',
      pincode: '342602',
      description: 'Drought-resilient Bajra pearl millet, royal cumin seeds, organic fenugreek, and cold-pressed yellow mustard.',
      cropTypes: ['Grains', 'Spices', 'Pulses'],
      farmingMethod: 'Natural / Permaculture',
      organicCertified: false,
      certifications: ['Rainfed Farm Verification'],
      yearsExperience: 15,
      farmSizeAcres: 18,
      verificationStatus: 'approved',
      rating: 4.6,
      reviewCount: 33,
      fulfilmentRate: 96,
      deliveryOptions: ['Scheduled delivery'],
      typicalDeliveryDays: '2 Days',
      minimumOrder: 150,
      profileImage: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Sun-baked aridity harvest naturally preserves aroma and grain density without chemical fungicides.',
      sourcingTransparency: 'Pure rain-fed desert crop varieties preserved over centuries.'
    }
  },
  {
    name: 'Madhab Das',
    email: 'madhab.das@farm.com',
    phone: '+91 94350 20304',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Brahmaputra Green Valley',
      location: 'Titabar',
      district: 'Jorhat',
      state: 'Assam',
      pincode: '785630',
      description: 'Artisanal single-estate orthodox green tea, Lakadong high-curcumin turmeric, and rare Black Jasmine rice.',
      cropTypes: ['Spices', 'Grains', 'Other'],
      farmingMethod: 'Organic',
      organicCertified: true,
      certifications: ['India Organic Certified', 'Fair Harvest'],
      yearsExperience: 10,
      farmSizeAcres: 11,
      verificationStatus: 'approved',
      rating: 4.8,
      reviewCount: 30,
      fulfilmentRate: 98,
      deliveryOptions: ['Scheduled delivery'],
      typicalDeliveryDays: '2-3 Days',
      minimumOrder: 250,
      profileImage: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Two leaves and a bud hand-plucked during prime morning mist, wood-fired micro batch processing.',
      sourcingTransparency: 'Certified organic agroecology supporting Brahmaputra river basin wildlife corridors.'
    }
  },
  {
    name: 'Laxman Rao',
    email: 'laxman.rao@farm.com',
    phone: '+91 94400 30405',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Godavari Rich Soils Farm',
      location: 'Kadiam',
      district: 'East Godavari',
      state: 'Andhra Pradesh',
      pincode: '533126',
      description: 'Fiery Guntur chillies, yellow split pigeon peas (Toor dal), sweet watermelons, and fresh green drumsticks.',
      cropTypes: ['Vegetables', 'Pulses', 'Spices'],
      farmingMethod: 'Conventional',
      organicCertified: false,
      certifications: ['AP State Agri Board'],
      yearsExperience: 17,
      farmSizeAcres: 16,
      verificationStatus: 'approved',
      rating: 4.5,
      reviewCount: 25,
      fulfilmentRate: 95,
      deliveryOptions: ['Local delivery', 'Scheduled delivery'],
      typicalDeliveryDays: '2 Days',
      minimumOrder: 120,
      profileImage: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      harvestPractices: 'Direct field grading, prompt shade-curing, breathable eco-friendly packaging.',
      sourcingTransparency: 'Rich fertile Godavari delta soil with drip-feed water conservation.'
    }
  },
  {
    name: 'Virendra Yadav (Pending Approval)',
    email: 'virendra.yadav@farm.com',
    phone: '+91 98390 40506',
    password: 'FarmerPass123!',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    farm: {
      farmName: 'Awadh Blossom Natural Orchard',
      location: 'Malihabad',
      district: 'Lucknow',
      state: 'Uttar Pradesh',
      pincode: '226102',
      description: 'Generational Dasheri mango orchard expanding into organic guava and winter mustard greens.',
      cropTypes: ['Fruits', 'Vegetables'],
      farmingMethod: 'Natural / Permaculture',
      organicCertified: false,
      certifications: [],
      yearsExperience: 5,
      farmSizeAcres: 7,
      verificationStatus: 'pending', // Pending verification for admin testing!
      verificationNotes: 'Newly applied, land documents submitted for verification.',
      rating: 0,
      reviewCount: 0,
      fulfilmentRate: 100,
      deliveryOptions: ['Local delivery'],
      typicalDeliveryDays: '1-2 Days',
      minimumOrder: 200,
      profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
      bannerImage: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80'
    }
  }
];

const customersData = [
  { name: 'Priya Sharma', email: 'priya.sharma@example.com', phone: '+91 98200 11001', city: 'Mumbai', state: 'Maharashtra', district: 'Mumbai Suburban', pincode: '400050', street: 'Bandra West, 14th Road' },
  { name: 'Arun Kumar', email: 'arun.kumar@example.com', phone: '+91 98450 22002', city: 'Bengaluru', state: 'Karnataka', district: 'Bengaluru Urban', pincode: '560038', street: 'Indiranagar, 100ft Road' },
  { name: 'Neha Gupta', email: 'neha.gupta@example.com', phone: '+91 98110 33003', city: 'New Delhi', state: 'Delhi', district: 'South Delhi', pincode: '110017', street: 'Saket, D-Block' },
  { name: 'Siddharth Nair', email: 'siddharth.nair@example.com', phone: '+91 94440 44004', city: 'Chennai', state: 'Tamil Nadu', district: 'Chennai', pincode: '600028', street: 'R.A. Puram, 3rd Cross' },
  { name: 'Ananya Roy', email: 'ananya.roy@example.com', phone: '+91 98300 55005', city: 'Kolkata', state: 'West Bengal', district: 'Kolkata', pincode: '700029', street: 'Southern Avenue, Lake Terrace' },
  { name: 'Vikram Joshi', email: 'vikram.joshi@example.com', phone: '+91 98230 66006', city: 'Pune', state: 'Maharashtra', district: 'Pune', pincode: '411004', street: 'Prabhat Road, Deccan' },
  { name: 'Kavita Reddy', email: 'kavita.reddy@example.com', phone: '+91 98490 77007', city: 'Hyderabad', state: 'Telangana', district: 'Hyderabad', pincode: '500034', street: 'Banjara Hills, Road No. 12' },
  { name: 'Rahul Mehta', email: 'rahul.mehta@example.com', phone: '+91 98240 88008', city: 'Ahmedabad', state: 'Gujarat', district: 'Ahmedabad', pincode: '380015', street: 'Satellite, Bodakdev' },
  { name: 'Deepika Rao', email: 'deepika.rao@example.com', phone: '+91 98480 99009', city: 'Visakhapatnam', state: 'Andhra Pradesh', district: 'Visakhapatnam', pincode: '530003', street: 'Waltair Uplands' },
  { name: 'Gaurav Verma', email: 'gaurav.verma@example.com', phone: '+91 98100 12345', city: 'Gurugram', state: 'Haryana', district: 'Gurugram', pincode: '122002', street: 'DLF Phase 2' },
  { name: 'Pooja Iyer', email: 'pooja.iyer@example.com', phone: '+91 94470 23456', city: 'Kochi', state: 'Kerala', district: 'Ernakulam', pincode: '682020', street: 'Panampilly Nagar' },
  { name: 'Manish Tiwari', email: 'manish.tiwari@example.com', phone: '+91 94150 34567', city: 'Lucknow', state: 'Uttar Pradesh', district: 'Lucknow', pincode: '226010', street: 'Gomti Nagar, Vibhuti Khand' },
  { name: 'Sneha Kulkarni', email: 'sneha.kulkarni@example.com', phone: '+91 98221 45678', city: 'Nashik', state: 'Maharashtra', district: 'Nashik', pincode: '422005', street: 'College Road' },
  { name: 'Rohan Banerjee', email: 'rohan.banerjee@example.com', phone: '+91 98310 56789', city: 'Chandigarh', state: 'Chandigarh', district: 'Chandigarh', pincode: '160019', street: 'Sector 19-B' },
  { name: 'Divya Menon', email: 'divya.menon@example.com', phone: '+91 94460 67890', city: 'Thiruvananthapuram', state: 'Kerala', district: 'Thiruvananthapuram', pincode: '695003', street: 'Kowdiar' },
  { name: 'Amit Saxena', email: 'amit.saxena@example.com', phone: '+91 98260 78901', city: 'Bhopal', state: 'Madhya Pradesh', district: 'Bhopal', pincode: '462016', street: 'Arera Colony, E-3' },
  { name: 'Megha Singhal', email: 'megha.singhal@example.com', phone: '+91 94141 89012', city: 'Jaipur', state: 'Rajasthan', district: 'Jaipur', pincode: '302004', street: 'C-Scheme, Subhash Marg' },
  { name: 'Kartik Bhat', email: 'kartik.bhat@example.com', phone: '+91 94482 90123', city: 'Mangaluru', state: 'Karnataka', district: 'Dakshina Kannada', pincode: '575003', street: 'Kadri Hills' },
  { name: 'Tanvi Sen', email: 'tanvi.sen@example.com', phone: '+91 98320 01234', city: 'Siliguri', state: 'West Bengal', district: 'Darjeeling', pincode: '734001', street: 'Sevoke Road' },
  { name: 'Vivek Chawla', email: 'vivek.chawla@example.com', phone: '+91 98150 12389', city: 'Amritsar', state: 'Punjab', district: 'Amritsar', pincode: '143001', street: 'Mall Road' }
];

module.exports = {
  categoriesData,
  adminData,
  farmersData,
  customersData
};